version: "2"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "100:8080"
    volumes:
      - ./uneplan:/var/www/uneplan
      - ./prod/nginx:/etc/nginx/conf.d
      - ./prod/logs:/var/logs/nginx
    depends_on:
      - django
  django:
    build: .
    restart: always
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py migrate && gunicorn StrategicPlanning.wsgi -w 8 -t 300 -b 0.0.0.0:8080"
    volumes:
      - ./uneplan:/var/www/uneplan
    expose:
     - "8080"
    depends_on:
     - db
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ./database-backup:/database-backup
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  postgres-config:
  postgres-data:
  postgres-logs: