# Generated by Django 3.0.2 on 2020-09-22 06:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('added_by_date', models.DateField(default=datetime.date.today)),
                ('modified_by_date', models.DateField(default=datetime.date.today)),
                ('deleted_by_date', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_added', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
